name: Version Packages

on:
  workflow_dispatch: {} # run manually from GitHub UI

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed so changesets can read history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --link-workspace-packages=false

      - name: Run version-packages
        run: pnpm run version-packages

      - name: Create Version Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'chore: version packages'
          branch: 'version-packages-update'
          title: 'chore: version packages'
          body: 'Automated PR with updated package versions from changesets'
